rvm:
  - 1.8.7
  - ree
  - 1.9.3

notifications:
  recipients:
    - support@typuscmf.com

branches:
  only:
    - master
    - 3-1-stable

before_script:
  - "psql -c 'create database typus_test;' -U postgres"
